sudo: false
language: node_js
node_js:
  - 4.0
before_script:
  - npm install -g mocha
  - npm mocha --version
  - npm install -g mocha-phantomjs
  - npm mocha-phantomjs --version
script: phantomjs test/UnitTest.js
