sudo: false
language: node_js
node_js:
  - 4.0
before_script:
  - npm install -g mocha --save-dev
  - npm install -g chai --save-dev
  - npm install -g mocha-phantomjs --save-dev
script: phantomjs test/test.js
